baseURL = "https://kaptajnbajer.github.io/what/"
title = "Project Title"
description = "En ædndring i Config?"
relativeURLs = true
theme = "theme" 
[params]
    authors = ["Virker den her del?"]
    notebook = "/explainer-notebook.html"
    data = "https://drive.google.com"
    github = "https://github.com/peterampazzo/project-website-template"
    [[params.nav]]
        label = "Data"
        link = "/data-description"
    [[params.nav]]
        label = "Network"
        link = "/network-analysis"
    [[params.nav]]
        label = "Text"
        link = "/text-analysis"

